public enum TokenType {
    LEFT_PARAN, RIGHT_PARAN, SEMICOLON, COMMA,PLUS, MINUS, MULTIPLY, DIVIDE, LESSERTHAN, GREATERTHAN, EQUALTO, LESSTHANOREQUALTO, GREATERTHANOREQUALTO, NOTEQUALTO,

    IDENTIFIER, LITERAL,

    INT, MAIN, FLOAT,IF, BEGIN, PRINTF, END
}